// This file simulates a backend API.
// Do not edit this file, the bugs are in the React component.

const weatherConditions = ['Sunny', 'Cloudy', 'Rainy', 'Windy', 'Stormy'];

// A map to store fake data to make it semi-consistent
const cityDataCache = new Map();

function getMockDataForCity(city) {
  if (cityDataCache.has(city)) {
    return cityDataCache.get(city);
  }

  const data = {
    city: city,
    temperature: Math.floor(Math.random() * 25 + 5), // Temp between 5°C and 30°C
    condition: weatherConditions[Math.floor(Math.random() * weatherConditions.length)],
    humidity: Math.floor(Math.random() * 50 + 40), // Humidity between 40% and 90%
    wind: Math.floor(Math.random() * 20 + 5), // Wind speed between 5 km/h and 25 km/h
  };
  cityDataCache.set(city, data);
  return data;
}

export const getWeatherData = (city) => {
  console.log(`API: Fetching weather for ${city}...`);

  return new Promise((resolve, reject) => {
    // Simulate network delay
    setTimeout(() => {
      // Simulate a potential API failure
      if (Math.random() > 0.9 && city === 'Tokyo') {
        reject(new Error('API is temporarily unavailable for Tokyo'));
      } else {
        resolve(getMockDataForCity(city));
      }
    }, 300 + Math.random() * 500);
  });
};
