// This file simulates a backend API.
// Do not edit this file, the bugs are in the React components.

const allJobs = [
  { id: 1, company: 'Photosnap', position: 'Senior Frontend Developer', role: 'Frontend', level: 'Senior', location: 'USA Only' },
  { id: 2, company: 'Manage', position: 'Fullstack Developer', role: 'Fullstack', level: 'Midweight', location: 'Remote' },
  { id: 3, company: 'Account', position: 'Junior Frontend Developer', role: 'Frontend', level: 'Junior', location: 'USA Only' },
  { id: 4, company: 'MyHome', position: 'Junior Frontend Developer', role: 'Frontend', level: 'Junior', location: 'USA Only' },
  { id: 5, company: 'Loop Studios', position: 'Software Engineer', role: 'Fullstack', level: 'Midweight', location: 'Worldwide' },
  { id: 6, company: 'FaceIt', position: 'Junior Backend Developer', role: 'Backend', level: 'Junior', location: 'UK Only' },
  { id: 7, company: 'Shortly', position: 'Junior Developer', role: 'Frontend', level: 'Junior', location: 'Worldwide' },
  { id: 8, company: 'Insure', position: 'Junior Frontend Developer', role: 'Frontend', level: 'Junior', location: 'USA Only' },
  { id: 9, company: 'Eyecam Co.', position: 'Full Stack Engineer', role: 'Fullstack', level: 'Midweight', location: 'Worldwide' },
  { id: 10, company: 'The Air Filter Company', position: 'Back-end Dev', role: 'Backend', level: 'Junior', location: 'Part-time' },
];

export const fetchJobs = (filters) => {
  console.log('API: Fetching jobs with filters:', filters);
  
  return new Promise((resolve) => {
    let filteredJobs = [...allJobs];
    
    if (filters) {
      if (filters.role) {
        filteredJobs = filteredJobs.filter(job => job.role === filters.role);
      }
      if (filters.level) {
        filteredJobs = filteredJobs.filter(job => job.level === filters.level);
      }
      if (filters.location && filters.location.trim() !== '') {
        filteredJobs = filteredJobs.filter(job => 
          job.location.toLowerCase().includes(filters.location.toLowerCase())
        );
      }
    }

    // Simulate network delay
    setTimeout(() => {
      resolve(filteredJobs);
    }, 300);
  });
};