// This file simulates a backend API.
// Do not edit this file, the bugs are in the React components.

const mockDatabase = {
  chicken: [
    { id: 1, title: 'Classic Roast Chicken', image: 'https://i.imgur.com/sx3vKzM.jpeg', sourceUrl: '#' },
    { id: 2, title: 'Chicken Alfredo Pasta', image: 'https://i.imgur.com/KxVbI4J.jpeg', sourceUrl: '#' },
    { id: 3, title: 'Spicy Chicken Tacos', image: 'https://i.imgur.com/L7VLWzQ.jpeg', sourceUrl: '#' },
  ],
  beef: [
    { id: 4, title: 'Hearty Beef Stew', image: 'https://i.imgur.com/nJtvBCp.jpeg', sourceUrl: '#' },
    { id: 5, title: 'Perfect Beef Burgers', image: 'https://i.imgur.com/nI4n57I.jpeg', sourceUrl: '#' },
  ],
  tofu: [
    { id: 6, title: 'Crispy Pan-Fried Tofu', image: 'https://i.imgur.com/o7bXcfB.jpeg', sourceUrl: '#' },
  ]
};

export const fetchRecipesByIngredient = (ingredient) => {
  console.log(`API: Fetching recipes for "${ingredient}"...`);
  const searchTerm = ingredient.toLowerCase();

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (searchTerm === 'error') {
        reject(new Error('Failed to fetch from API.'));
      } else if (mockDatabase[searchTerm]) {
        resolve({ recipes: mockDatabase[searchTerm] });
      } else {
        resolve({ recipes: [] }); // No results
      }
    }, 400 + Math.random() * 600);
  });
};